// <auto-generated />
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SemanticAlgebra.SourceGenerator.Models;
using System.Text;

namespace SemanticAlgebra.SourceGenerator.Generators;

/// <summary>
/// Generates builder methods (Option.B class)
/// </summary>
public static class BuilderGenerator
{
    /// <summary>
    /// Generates the complete B class with all builder methods
    /// </summary>
    public static string GenerateBuildersClass(SemanticKindInfo kindInfo)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using SemanticAlgebra;");
        sb.AppendLine();
        
        if (!string.IsNullOrEmpty(kindInfo.Namespace))
        {
            sb.AppendLine($"namespace {kindInfo.Namespace};");
            sb.AppendLine();
        }
        
        sb.AppendLine($"partial class {kindInfo.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// {kindInfo.ClassName} data value builders");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class B");
        sb.AppendLine("    {");
        
        // Generate builder methods
        foreach (var method in kindInfo.SemanticMethods)
        {
            var caseInfo = new SemanticCaseGenerationInfo(kindInfo, method);
            sb.AppendLine(caseInfo.GetBuilderMethodSource());
        }
        
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}
